name: dbus headless check

on: [ push ]

jobs:
  build_java:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Install libdbus Environment
        run: |
          sudo apt update
          sudo apt install gnome-keyring libsecret-tools dbus-x11
          if [ -e /usr/bin/gnome-keyring-daemon ]; then
            if [ ! -z "`kill -0 $GNOME_KEYRING_PID 2>&1`" ]; then
              eval 'dbus-launch --sh-syntax'
              echo ----------------------------------------------------
              echo $(dbus-launch --sh-syntax)
              echo ----------------------------------------------------
              eval $(printf 'keyring_password' | /usr/bin/gnome-keyring-daemon --unlock --components=pkcs11,secrets,ssh)
              export SSH_AUTH_SOCK
            fi
          fi

      - name: Check dbus config
        run: printf "apassword" | secret-tool store --label="test" foo bar
